/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wildventory_admin;

import hal_utama.halaman_utama;
import hal_utama.login;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class halaman_admin extends javax.swing.JFrame {

    /**
     * Creates new form halaman_admin
     */
    public halaman_admin() {
        initComponents();
        setIcon();
    }
public void bckup() {
try{
    
       Connection con = DriverManager.getConnection("jdbc:h2:./database/wildventory", "admin", "" );
       Statement stmt = con.createStatement();
       con.prepareStatement("BACKUP TO 'backup/backup_database.zip'").executeUpdate();
       JOptionPane.showMessageDialog(this,"Backup terimpan di backup/backup_database.zip.");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Pastikan program di 'run as administrator' agar proses backup berhasil.");
        }
}


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        hover_beranda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inventori = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tentang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        keluar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        beranda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(207, 241, 239));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Artboard 1.png"))); // NOI18N
        sidepanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, -1, -1));

        copyright.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        copyright.setForeground(new java.awt.Color(63, 63, 63));
        copyright.setText("RH ©2020 1.0.0");
        sidepanel.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 511, -1, -1));

        hover_beranda.setBackground(new java.awt.Color(167, 211, 208));
        hover_beranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (1).png"))); // NOI18N
        jLabel2.setText("  Beranda");
        hover_beranda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));

        sidepanel.add(hover_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 40));

        inventori.setBackground(new java.awt.Color(207, 241, 239));
        inventori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoriMouseClicked(evt);
            }
        });
        inventori.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/work.png"))); // NOI18N
        jLabel3.setText("  Data Inventori");
        inventori.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        sidepanel.add(inventori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        tentang.setBackground(new java.awt.Color(207, 241, 239));
        tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tentangMouseClicked(evt);
            }
        });
        tentang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        jLabel6.setText("  Tentang Aplikasi");
        tentang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, -1));

        sidepanel.add(tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 40));

        keluar.setBackground(new java.awt.Color(207, 241, 239));
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        keluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel4.setText("  Keluar");
        keluar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, -1));

        sidepanel.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 40));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 540));

        panel_menu.setBackground(new java.awt.Color(207, 241, 239));

        beranda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        beranda.setForeground(new java.awt.Color(63, 63, 63));
        beranda.setText("Beranda");

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(beranda)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(beranda)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        bg.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 640, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Halo, semangat untuk hari ini!");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        backup.setText("Backup Database");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });
        bg.add(backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 140, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Halo admin,");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Rutin backup database ya!");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Untuk restore, replace file backup-an mu ke file database ya.");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoriMouseClicked
this.dispose();
new datainventori().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_inventoriMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
int jawab = JOptionPane.showOptionDialog(this, "Ingin Keluar?", "Keluar",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE, null, null, null);
if (jawab == JOptionPane.YES_OPTION) {
    System.exit(0);
}
else if (jawab == JOptionPane.NO_OPTION) {         // TODO add your handling code here:
    
    }//GEN-LAST:event_keluarMouseClicked
    }
    private void tentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tentangMouseClicked
this.dispose();
        new tentang().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_tentangMouseClicked

    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
bckup();        // TODO add your handling code here:
    }//GEN-LAST:event_backupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backup;
    private javax.swing.JLabel beranda;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel copyright;
    private javax.swing.JPanel hover_beranda;
    private javax.swing.JPanel inventori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel keluar;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel tentang;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icons.png")));
    }

}
