/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wildventory_admin;

import hal_utama.halaman_utama;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class tentang extends javax.swing.JFrame {

    /**
     * Creates new form tentang
     */
    public tentang() {
        initComponents();
        setIcon();
        
    }
    public void link_privacy(){
        try {
            String myurl = "https://github.com/rizikhanafi/wildventory/blob/master/privacy.md";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(myurl));
        } catch (Exception e2) {
            e2.printStackTrace();
        }
        
    }
    public void link_github () {
        try {
            String myurl = "https://github.com/rizikhanafi";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(myurl));
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }
    public void link_terms () {
        try {
            String myurl = "https://github.com/rizikhanafi/wildventory/blob/master/terms.md";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(myurl));
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }
    public void link_ig () {
        try {
            String myurl = "https://instagram.com/rizikhanafi";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(myurl));
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        privacy_popup = new javax.swing.JDialog();
        bg_privacy = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        berandaa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inventori = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hover_tentang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        keluar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        beranda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        github = new javax.swing.JButton();
        privacy = new javax.swing.JButton();
        github1 = new javax.swing.JButton();
        github2 = new javax.swing.JButton();

        privacy_popup.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        privacy_popup.setTitle("Privacy & Policy");

        bg_privacy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Privacy & Policy");
        bg_privacy.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        javax.swing.GroupLayout privacy_popupLayout = new javax.swing.GroupLayout(privacy_popup.getContentPane());
        privacy_popup.getContentPane().setLayout(privacy_popupLayout);
        privacy_popupLayout.setHorizontalGroup(
            privacy_popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_privacy, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        privacy_popupLayout.setVerticalGroup(
            privacy_popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(privacy_popupLayout.createSequentialGroup()
                .addComponent(bg_privacy, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(207, 241, 239));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Artboard 1.png"))); // NOI18N
        sidepanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, -1, -1));

        copyright.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        copyright.setForeground(new java.awt.Color(63, 63, 63));
        copyright.setText("RH ©2020 1.0.0");
        sidepanel.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 511, -1, -1));

        berandaa.setBackground(new java.awt.Color(207, 241, 239));
        berandaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaaMouseClicked(evt);
            }
        });
        berandaa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (1).png"))); // NOI18N
        jLabel2.setText("  Beranda");
        berandaa.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));

        sidepanel.add(berandaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 40));

        inventori.setBackground(new java.awt.Color(207, 241, 239));
        inventori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoriMouseClicked(evt);
            }
        });
        inventori.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/work.png"))); // NOI18N
        jLabel3.setText("  Data Inventori");
        inventori.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        sidepanel.add(inventori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        hover_tentang.setBackground(new java.awt.Color(167, 211, 208));
        hover_tentang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        jLabel6.setText("  Tentang Aplikasi");
        hover_tentang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, -1));

        sidepanel.add(hover_tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 40));

        keluar.setBackground(new java.awt.Color(207, 241, 239));
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        keluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel4.setText("  Keluar");
        keluar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, -1));

        sidepanel.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 40));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 540));

        panel_menu.setBackground(new java.awt.Color(207, 241, 239));

        beranda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        beranda.setForeground(new java.awt.Color(63, 63, 63));
        beranda.setText("Tentang Aplikasi");

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(beranda)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(beranda)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        bg.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 640, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Bagaimana aplikasi ini bisa dibuat?");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Versi Aplikasi : 1.0.0");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Lisensi : Tidak Ada (Open Source)");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        github.setText("Terms of Service");
        github.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubActionPerformed(evt);
            }
        });
        bg.add(github, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, 30));

        privacy.setText("Privacy & Policy");
        privacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacyActionPerformed(evt);
            }
        });
        bg.add(privacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 120, 30));

        github1.setText("Github");
        github1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                github1ActionPerformed(evt);
            }
        });
        bg.add(github1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 110, 30));

        github2.setText("Instagram");
        github2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                github2ActionPerformed(evt);
            }
        });
        bg.add(github2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoriMouseClicked
        this.dispose();
        new datainventori().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_inventoriMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        int jawab = JOptionPane.showOptionDialog(this, "Ingin Keluar?", "Keluar",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE, null, null, null);
if (jawab == JOptionPane.YES_OPTION) {
    System.exit(0);
}       // TODO add your handling code here:
    }//GEN-LAST:event_keluarMouseClicked

    private void berandaaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaaMouseClicked
this.dispose();
        new halaman_admin().setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_berandaaMouseClicked

    private void privacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacyActionPerformed
        link_privacy();       // TODO add your handling code here:
    }//GEN-LAST:event_privacyActionPerformed

    private void github2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_github2ActionPerformed
link_ig();        // TODO add your handling code here:
    }//GEN-LAST:event_github2ActionPerformed

    private void github1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_github1ActionPerformed
link_github();        // TODO add your handling code here:
    }//GEN-LAST:event_github1ActionPerformed

    private void githubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubActionPerformed
link_terms();        // TODO add your handling code here:
    }//GEN-LAST:event_githubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tentang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beranda;
    private javax.swing.JPanel berandaa;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg_privacy;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton github;
    private javax.swing.JButton github1;
    private javax.swing.JButton github2;
    private javax.swing.JPanel hover_tentang;
    private javax.swing.JPanel inventori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel keluar;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JButton privacy;
    private javax.swing.JDialog privacy_popup;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icons.png")));
    }
}
